apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: C:\Users\hafid\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -o zeroai --namespace zeroai
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: minio
  name: minio
  namespace: zeroai
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hafid\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -o zeroai --namespace zeroai
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_PASSWORD
              value: acces@miniowebai
            - name: MINIO_ROOT_USER
              value: minioadmin
          image: minio/minio
          name: minio-webai
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-data
      restartPolicy: Always
      volumes:
        - name: minio-data
          hostPath:
            path: /mnt/data/minio  # path di node, ganti sesuai kebutuhan
            type: DirectoryOrCreate
  # volumeClaimTemplates:
  #   - metadata:
  #       name: minio-data
  #       labels:
  #         io.kompose.service: minio-claim0
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi
