apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: C:\Users\hafid\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -o zeroai --namespace zeroai
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: zeroai
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hafid\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -o zeroai --namespace zeroai
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: webai
            - name: MYSQL_PASSWORD
              value: p@ssw0rd!webai
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: webai
          image: mysql:8.0
          name: mysql-webai
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      restartPolicy: Always
      volumes:
        - name: mysql-data
          hostPath:
            path: /mnt/data/mysql  # path di node, ganti sesuai kebutuhan
            type: DirectoryOrCreat
  # volumeClaimTemplates:
  #   - metadata:
  #       name: mysql-data
  #       labels:
  #         io.kompose.service: mysql-claim0
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 10Gi