apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hafid\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c -o zeroai --namespace zeroai
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: webai
  name: webai
  namespace: zeroai
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: webai

  #
